### ISSUE TITLE
Line labels

### ISSUE THREAD

**Issue by erwinstuijt** [JunfengGaolab/CropRowDetection#2]
From the README:
'Numeric values of the labelled coordinates are stored in .mat files. All the label coordinates in train dataset are stored in a single .mat file. The label coordinates in test dataset are stored in 10 separate .mat files.' 
Could you share the code with which you converted these tables to the segmentation maps. I would like to understand how the   cells, e.g. [1.0509e+03,35.3804;1.1440e+03,1.0637e+03], represent lines.

**Comment by Rajitha159** [comment]
The labels are done using the MATLAB video labeller tool on unresized original images. You have to first download the original images from the below links.
https://drive.google.com/file/d/1-11NX4hdVav5s6Wf0naG6m6Juup2w4HH/view?usp=sharing
https://drive.google.com/file/d/1DyjCnJdRVWxN51DKG2NQKVlbsMl9HLKv/view?usp=sharing

Then use the [MATLAB code](https://github.com/JunfengGaolab/CropRowDetection/blob/main/codes/label_image_gen.m) provided to generate ground truth image masks. Note that you have to uncomment _% Fix missing paths if needed %_ section of the code to update the location of the original image directory in your computer. The respective MATLAB data file must be loaded in each execution and the original image directory must be provided for each execution.

**Comment by rajithadesilva** [comment]
The labels are done using the MATLAB video labeller tool on unresized original images. You have to first download the original images from the below links.
https://drive.google.com/file/d/1-11NX4hdVav5s6Wf0naG6m6Juup2w4HH/view?usp=sharing
https://drive.google.com/file/d/1DyjCnJdRVWxN51DKG2NQKVlbsMl9HLKv/view?usp=sharing

Then use the [MATLAB code](https://github.com/JunfengGaolab/CropRowDetection/blob/main/codes/label_image_gen.m) provided to generate ground truth image masks. Note that you have to uncomment _% Fix missing paths if needed %_ section of the code to update the location of the original image directory in your computer. The respective MATLAB data file must be loaded in each execution and the original image directory must be provided for each execution.

**Comment by estuijt** [comment]
Hello,
It is clear to me how the raw images from https://drive.google.com/file/d/1-11NX4hdVav5s6Wf0naG6m6Juup2w4HH/view match up with the labels in CropRowDetection/Dataset/Train Dataset/labels.mat
I also want to match the images from https://drive.google.com/file/d/1DyjCnJdRVWxN51DKG2NQKVlbsMl9HLKv/view?usp=sharing with all label files from CropRowDetection/Dataset/Test Dataset/Labels/, however the structure of how labels from those files match up with the images are not clear. Is there something I am missing?

Than another small question: in https://arxiv.org/pdf/2209.04278.pdf you mentioned that the camera has a pitch of -25 degrees. Is there also a camera height known for this camera? And a row distance of the sugar beets in this images? With this I want to calculate detection error in meters.
